name: amde_haymanot_abalat_guday
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  animate_do: ^4.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.0
  syncfusion_flutter_charts: ^30.1.41
  percent_indicator: ^4.2.5
  bottom_navy_bar: ^6.0.0
  sliding_clipped_nav_bar: ^3.1.1
  convex_bottom_bar: ^3.2.0
  flutter_speed_dial: ^7.0.0

  # State Management & Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^16.0.0
  provider: ^6.1.2

  # Networking & Data
  supabase_flutter: ^2.5.0
  cached_network_image: ^3.3.1
  http: ^1.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

  # Cloudinary SDK
  cloudinary_public: ^0.23.1

  # Media & Content
  image_picker: ^1.1.2
  youtube_player_flutter: ^9.0.0
  youtube_player_iframe: ^5.1.2
  video_player: ^2.8.6
  flutter_quill: ^11.4.2
  youtube_explode_dart: ^2.5.2

  # Utility & Other
  url_launcher: ^6.3.0
  intl: ^0.20.2
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  open_file: ^3.3.2
  mime: ^2.0.0
  table_calendar: ^3.1.2
  universal_html: ^2.2.4
  flutter_downloader: ^1.12.0
  flutter_localization: ^0.3.3
  timeago: ^3.7.1
  ethiopian_datetime_picker: ^0.0.2+1
  abushakir: ^1.0.0
  calendar_picker_ghe: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --- FINAL CORRECTED ICON CONFIGURATION ---
# This setup assumes you have:
# 1. A square master logo at 'assets/icon/logo.png' (e.g., 1024x1024)
# 2. A circular master logo at 'assets/icon/logo_round.png' (e.g., 1024x1024)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_foreground: "assets/icon/logo.png"
  adaptive_icon_background: "#FF012564" # Change to your brand's background color
  android_round:
    image_path: "assets/icon/logo_round.png"

# Dependency override
dependency_overrides:
  http: ^1.2.1
  
flutter:
  uses-material-design: true

  # --- FINAL CORRECTED ASSETS SECTION ---
  # This assumes your .env file is named 'dotenv' (without a dot)
  # for better web compatibility.
  assets:
    - dotenv
    - assets/images/
    - assets/icon/